### ISSUE TITLE
ValueError: hero 0 not found in state

### ISSUE THREAD

**Issue by TimZaman** [TimZaman/dotaservice#10]
During a random training on K8s i saw. It reports a pre-game game state without _any_ units. Obviously that's not a controllable situation, as there is nothing to control or act upon. So we should only push worldstates that have controllable entities.
```
Traceback (most recent call last):
  File "client.py", line 401, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "client.py", line 365, in main
    actor_output = await asyncio.gather(*[a() for a in actors])
  File "client.py", line 297, in __call__
    action = select_action(obs, step=step)
  File "client.py", line 150, in select_action
    unit = get_hero_unit(world_state)
  File "client.py", line 209, in get_hero_unit
    raise ValueError("hero {} not found in state:\n{}".format(id, state))
ValueError: hero 0 not found in state:
team_id: 2
game_time: 73.89921569824219
dota_time: -87.30003356933594
game_state: 4
hero_pick_state: 1
time_of_day: 0.0
glyph_cooldown: 341.1992492675781
glyph_cooldown_enemy: 341
players {
  player_id: 0
  team_id: 2
}
players {
  player_id: 1
  team_id: 2
}
players {
  player_id: 2
  team_id: 2
}
players {
  player_id: 3
  team_id: 2
}
players {
  player_id: 4
  team_id: 2
}
players {
  player_id: 5
  team_id: 3
}
players {
  player_id: 6
  team_id: 3
}
players {
  player_id: 7
  team_id: 3
}
players {
  player_id: 8
  team_id: 3
}
players {
  player_id: 9
  team_id: 3
}
```

**Comment by Nostrademous** [comment]
Yes, this started happening as of Patch 7.0 and is an lag/hiccup in the Dota2 system which in turn prevents the protobuf they are sending getting filled, but they still send it every X frames per the launch configuration options so you basically can get an empty frame.

**Comment by Nostrademous** [comment]
I think they made bots wear the fancy high-particle model armor to entice people to see it and want it and buy it. Those models have possibly large materials and sprite files and are loaded when the bot selects a hero. If all 5 bots on a team select a hero at the same time (and bots do that by default) the load on the system is larger and could lead to a lag. That’s my guess. Did it only happen on games you rendered?

**Comment by TimZaman** [comment]
No i only ever happened running remote containers which have a pretty slow
clockspeed and have cpu restrictions and might not keep up with things well.

**Comment by TimZaman** [comment]
Patched in https://github.com/TimZaman/dotaservice/commit/72838d4a76926ebd6785c8734226514059b30a2a
