### ISSUE TITLE
Client PIP Requirements

### ISSUE THREAD

**Issue by Nostrademous** [TimZaman/dotaservice#14]
Can you add to the requirements.txt or add a requirements.pip specifying all other pip packages being used by the client.py and other pieces?

Your recent check in added google.cloud for example but seems I don't have the right pip package installed.

  Downloading https://files.pythonhosted.org/packages/ba/b1/7c54d1950e7808df06642274e677dbcedba57f75307adf2e5ad8d39e5e0e/google_cloud-0.34.0-py2.py3-none-any.whl
Installing collected packages: google.cloud
Successfully installed google.cloud

Andrzejs-MacBook-Pro:dotaservice andrzej.gorski$ python3.7 examples/client.py 
Traceback (most recent call last):
  File "examples/client.py", line 10, in <module>
    from google.cloud import storage
ModuleNotFoundError: No module named 'google.cloud'

Turns out the actual pip is google-cloud-storage, a requirements.pip would have made that easier.

Other pip packages currently not mentioned include: tensorboardX, torch

I can do this but not sure if you care about specific versions or not

**Comment by Nostrademous** [comment]
I mean just listing them in a file so you can run ‘pip install -r filename’ and be done rather than rerunning the client numerous times and waiting for exception to be thrown when module not found.

**Comment by lenLRX** [comment]
separate requirements.txt for client.py is good, but never pollute the requirements.txt for package installation
