### ISSUE TITLE
Create self-play

### ISSUE THREAD

**Issue by Nostrademous** [TimZaman/dotaservice#28]
- [x] Determine how and where we want to separate Dire & Radiant data/logic. We could just create two instances of DotaService class (and add specifying teamID and associated port to listen on as class parameters) and create an array/tuple of tasks and make the loop run on it (https://github.com/TimZaman/dotaservice/blob/master/dotaservice/dotaservice.py#L508-L515). However, we could also make it internal to the DotaService class through better functionalization.

- [ ] Separate Dire & Radiant example clients

**Comment by TimZaman** [comment]
Currently working on this, should be done within the week. Also i entirely reorganized the example code. i added another 'optimizer-service' that scales very well.

**Comment by TimZaman** [comment]
K got it working now! Need to change the policy accordingly. Its very messy
code atm bc im traveling but will push to some branch soon.
