### ISSUE TITLE
the AI vs AI play mode

### ISSUE THREAD

**Issue by sijiaxu** [TimZaman/dotaservice#30]
Hi guys, 

I really curious about how some specific game modes are created in dotaservice (eg, the scripted ai vs scripted ai mode, the scripted ai vs buildin ai mode)? I go through some related code, maybe the game mode is specified in https://github.com/TimZaman/dotaservice/blob/80168b8c5253655af0d50a1f80a7ae31ee8391c0/dotaservice/dotaservice.py#L196-L230 I also notice the self.game_mode enum definition, but according to https://dota2.gamepedia.com/Game_modes#Captains_Draft  , I don't find the scripted ai play mode.

before come to dotaservice repo, I has googled a lot and try to find the solution to create the offline scripted ai vs scripted ai mode in lobby, but it seems current dota2 client disable the offline lobby creation and I can't get round this issue.

so I wonder how you guys slove this problem and if it is sloved by the command line paramter passed to dota2 client, where do you find the corresponding wiki/doc?

 Thanks!

**Comment by TimZaman** [comment]
I added a HostMode called 'gui_menu' with whicj you get the dota menu and create custom lobby. That will then use the dotaservice bots. I am currently refactoring dotaservice to allow scalable self play

**Comment by sijiaxu** [comment]
https://github.com/TimZaman/dotaservice/blob/fb38bfb38ac4fa9fe353cf4cc6fc632e23225c3c/dotaservice/dotaservice.py#L222-L230
it seems the command line parameter only add "sv_lan 0" with 'gui_menu' mode, so why this mode can create custom lobby and where is the related code?

**Comment by sijiaxu** [comment]
because I also want to deploy the pre-trained bot to play againest human, so such info is important to me..

**Comment by TimZaman** [comment]
The other modes add a specific map, the gui_menu mode does not, resulting
in the menu being prompted

**Comment by sijiaxu** [comment]
do you mean with gui_menu mode one must manually specify lobby's setting?
if that is true, is there a way to automatically create the game with this mode?

**Comment by sijiaxu** [comment]
I use the default game mode = DOTA_GAMEMODE_MO and GUI_MODE to test, it seems the AI in radiant and dire sides both use the local lua script, so the self-play mode is already supported, right?

**Comment by TimZaman** [comment]
yep

**Comment by sijiaxu** [comment]
great!
