### ISSUE TITLE
how to remove the fog of war?

### ISSUE THREAD

**Issue by sijiaxu** [TimZaman/dotaservice#36]
I use 'HOST_MODE_GUI' to launch dota, everything goes fine except I can't see the hero, it seems the fog of war cover the map.
I have tried add launch option '-render True' or '-allvision', but not work...

**Comment by Nostrademous** [comment]
Console command: ‘jointeam spec’

**Comment by sijiaxu** [comment]
Thanks!

**Comment by sijiaxu** [comment]
I notice in the previous version there is a function adding jointeam spec , it is much more convenient than typing in the game console, so why delete this?
https://github.com/TimZaman/dotaservice/blob/5184c8e3c85986e373353d938f0e57c581f25c2c/dotaservice/dotaservice.py#L161-173

**Comment by TimZaman** [comment]
That didnt work sadly

**Comment by sijiaxu** [comment]
ok, it doesn't matter.

**Comment by RylanSchaeffer** [comment]
Did you (or anyone) figure out how to submit Dota 2 console commands (e.g. spec_track) via `process.stdin.write()` or via terminal when launching Dota 2? I'm trying to automate changing the spectator mode, but none of the following worked when appended to the end of my terminal command:

`+dota_spectator_mode 3`
`-dota_spectator_mode 3`
`dota_spectator_mode 3`

**Comment by TimZaman** [comment]
No stdin write doesnt work if the gui is enabled

**Comment by RylanSchaeffer** [comment]
What about the second part of the question? Why do some console commands work when Dota is launched from terminal (e.g. `+dota_spectator_increasereplayspeed) but not others (e.g. `dota_spectator_mode 3`)?
