### ISSUE TITLE
lane creep not spawn

### ISSUE THREAD

**Issue by sijiaxu** [TimZaman/dotaservice#37]
I test the game mode = DOTA_GAMEMODE_MO and game mode = DOTA_GAMEMODE_1V1MID, but sometimes the lane creep doesn't spawn, do I miss something?

**Comment by sijiaxu** [comment]
in DOTA_GAMEMODE_1V1MID, after 3 minutes there is no lane creep, but has natural creep. 
In DOTA_GAMEMODE_MO, it is fine,  the lane creep has spawned after 30s.

I saw your dota client use the DOTA_GAMEMODE_1V1MID mode, do you also not has the lane creep?

**Comment by TimZaman** [comment]
i always have the creeps. make sure to have the host_timescale to 1. If you
have it too high the game bugs out without creeps. also make sure to turn
steam on.

**Comment by sijiaxu** [comment]
https://github.com/TimZaman/dotaservice/blob/5a413e3ae2290e8aed65b56da9e1550949a78d59/dotaservice/dotaservice.py#L211
this option seems has conflict with DOTA_GAMEMODE_1V1MID mode, with this option, no courier and after 90s no creep in the middle lane. without this option, everything is fine.

**Comment by TimZaman** [comment]
Weird, because i'm playing 1v1 mid with that option in all the time..

**Comment by sijiaxu** [comment]
maybe the difference in the dota2 client version? do you keep updating the client?
