### ISSUE TITLE
can not get the enemy lane creep info in world state

### ISSUE THREAD

**Issue by sijiaxu** [TimZaman/dotaservice#41]
I use the observe rpc with the dire team id, all info in the returned world state is ok, except there are no enemy(radiant) lane creep info, but actually the radiant lane creep is in our sight.

do you encounter this problem?

**Comment by TimZaman** [comment]
No? How did you observe this issue

**Comment by sijiaxu** [comment]
I am writing a script bot. first I order the NeverMore to move to the dire's first middle tower, it's ok.
then after 90s, the lane creep of both side are battling in the middle, but from the observation, it doesn't have the LANE_CREEP unittype and team_id = TEAM_RADIANT unit in the observation.units.

I use the GameConfig(ticks_per_observation=5, host_mode=1, game_mode=DOTA_GAMEMODE_1V1MID, host_timescale=3) to start the game
and observe(ObserveConfig(team_id=TEAM_DIRE) to get the world state

**Comment by sijiaxu** [comment]
the problem is in world state's queue, each observe function call only remove one observation from queue, the queue will soon stack lots of state, and what observe function return is lagging behind.
