### ISSUE TITLE
Dota2 Docker Error

### ISSUE THREAD

**Issue by Nostrademous** [TimZaman/dotaservice#48]
With patch 7.21 I tried to rebuild the dota2 docker container after deleting the old image and get an error. Not sure the cause:

```
Success! App '570' fully installed.
Updating Workshop items for App '570'.
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
contentmanifest.cpp (650) : Assertion Failed: !m_bIsFinalized
 Update state (0x61) downloading, progress: 21.09 (31200656 / 147970880)
 Update state (0x61) downloading, progress: 48.39 (71596542 / 147970880)
 Update state (0x61) downloading, progress: 64.85 (95956964 / 147970880)
 Update state (0x61) downloading, progress: 81.15 (120074212 / 147970880)
 Update state (0x61) downloading, progress: 98.58 (145873728 / 147970880)
Error processing tar file(exit status 1): write /root/Steam/steamapps/common/dota 2 beta/game/dota/pak01_144.vpk: no space left on device
```

Command was:
`docker build -t dota . -f docker/Dockerfile-dota --build-arg user=$STEAM_ID --build-arg pwd=$STEAM_PWD --build-arg guard=<CODE>`

I'm surprised by the `no space left on device`

I have over 700GB left on my laptop's SSD Flash drive so... must be docker container issue

**Comment by TimZaman** [comment]
You just have no space (in your vm)

**Comment by Nostrademous** [comment]
Hm... apparently docker on OSX has some issues with size building new containers if they over-write old containers and space is limited.

Doing a `docker system prune -a` and rebuilding fixed the issue.
