### ISSUE TITLE
dota2 docker running problem

### ISSUE THREAD

**Issue by sijiaxu** [TimZaman/dotaservice#54]
recently I rebuild the docker image, but after launching dota2, it reports a network error
![QQ截图20190311115442](https://user-images.githubusercontent.com/12146120/54099521-b2103a80-43f4-11e9-8a34-9cb6c2dc689f.png)

it seems some recent dota2's update cause this issue, any idea about how to resolve this?

**Comment by TimZaman** [comment]
Weird.. Works for me (latest version, with mars and all..). Launching
docker, try the docker run and add `--net=host`

**Comment by sijiaxu** [comment]
still not work...do you use the same dockfile in the repo?

**Comment by TimZaman** [comment]
Yep

**Comment by Passerby** [comment]
+1

**Comment by TimZaman** [comment]
I'll check it out tonight.

**Comment by TimZaman** [comment]
Fixed. With the latest update they require the steamlib to be found in the path. Accounted for that now in the dockerfile.

**Comment by sijiaxu** [comment]
thanks！

**Comment by Passerby** [comment]
cool!

**Comment by TimZaman** [comment]
Thanks for reporting guys, keep it coming.
