### ISSUE TITLE
Render in Macbook pro

### ISSUE THREAD

**Issue by wwxFromTju** [TimZaman/dotaservice#57]
Hi, @Nostrademous :

I use your fork version. It work good for my MacBook Pro. And I want to know, how to render the game? It like headless version.

**Comment by TimZaman** [comment]
Just use the render option in the proto right? Make sure steam is on or it wont work.

**Comment by wwxFromTju** [comment]
Hi，Thank you for your reply so quickly.

Can you be more detailed?

**Comment by TimZaman** [comment]
See https://github.com/TimZaman/dotaservice/blob/dfe882362c96b9979614abccf71fc9dcd6f8294b/dotaservice/protos/DotaService.proto#L142

**Comment by wwxFromTju** [comment]
Hi, it can start the window, and I can't find the hero. It look like hero is in the In the fog。

<img width="1253" alt="屏幕快照 2019-07-07 下午3 21 14" src="https://user-images.githubusercontent.com/14865611/60765306-1608ee00-a0cb-11e9-90a0-d963615baded.png">

**Comment by TimZaman** [comment]
Oh yeah you need to do a console xommand to get rid of the fog of war..
forgot what it was. Fog off maybe? Dont recall

**Comment by Nostrademous** [comment]
It was `jointeam spec` no?
