### ISSUE TITLE
How can i know a unit is visible to a team?

### ISSUE THREAD

**Issue by lenLRX** [TimZaman/dotaservice#58]
it seems that the observe() can get all units in the game. But if I pass a handle in DOTA_UNIT_ORDER_ATTACK_TARGET action which is not in bot's vision,  the GetBotByHandle will fail (and it should fail).
Thus I need a way to know if a unit is visible to bot.

**Comment by TimZaman** [comment]
Hi! That information is in your observation protobuf. That lists all units
visible.

**Comment by lenLRX** [comment]
ok i got it. The unexpected units were enemy buildings and they should be in my vision.
