### ISSUE TITLE
Is there an enum for team_id attribute?

### ISSUE THREAD

**Issue by lenLRX** [TimZaman/dotaservice#6]
found DOTA_GC_TEAM in dota_shared_enums.proto,  but it seems not the enum of units.team_id, since the units.team_id {good_guy:2, bad_guy:3}

**Comment by TimZaman** [comment]
Hi! What is the question exactly?

**Comment by TimZaman** [comment]
Good question! You can find this out by printing out a message.

**Comment by TimZaman** [comment]
I think it's a LUA thing, it's not described in any protobuf, i went through all of em.

**Comment by Nostrademous** [comment]
They don't have an ENUM for it, but it's trivial to add it to their proto structure with no impact.

**Comment by TimZaman** [comment]
Dont wanma touch those protos
