### ISSUE TITLE
where does the proto files come from?

### ISSUE THREAD

**Issue by lenLRX** [TimZaman/dotaservice#60]
I was parsing dota2 replays using clarity. And I found proto files in this project useful, especially [meaning of enums](https://github.com/TimZaman/dotaservice/blob/master/dotaservice/protos/dota_gcmessages_common_bot_script.proto#L500).
But some info is still missing, for example the meaning and range of rune types.
Thus I am curious where does this info comes from and if I can get more/latest info by my self.

**Comment by Delaunay** [comment]
You can get them [here][1]

[1]: https://github.com/SteamDatabase/Protobufs/tree/master/dota2

**Comment by lenLRX** [comment]
> You can get them [here](https://github.com/SteamDatabase/Protobufs/tree/master/dota2)

Got it! Thanks
