### ISSUE TITLE
Kubarnetes

### ISSUE THREAD

**Issue by Nostrademous** [TimZaman/dotaservice#7]
Since you mention this is your notes - my company posted a blog post on this topic a while back. I, personally, am not the guy familiar or responsible for this, but I mention it as I could reach out for help if we/you want to ever scale to that level.

https://www.twosixlabs.com/automated-docker-deployment-kubernetes-buildbot/

**Comment by TimZaman** [comment]
Im already running on kubernetes :)

**Comment by Nostrademous** [comment]
Cool. I shot you an email on the github listed associated email so we can chat more without abusing the concept of Issues.
